### ISSUE TITLE
Dividend distribution function – monthly profit sharing with all token holders.

### ISSUE THREAD

**Issue by thomsonimjd** [OpenZeppelin/zeppelin-solidity#658] opened 2018-01-09 06:29 UTC
All tokens holder get dividend based on no. of tokens held (i.e. 10% of tokens = 10% dividend)

Above is my requirement to do the monthly profit sharing concept.  It would be better if you could give me any sampls on this case or already availble in the open zeppelin contracts.
Thanks in advance

**Comment by frangio** [comment] 2018-01-09 19:14
Closed as a duplicate of #557. Feel free to discuss ideas over there!

**Closed by frangio** 2018-01-09 19:14 UTC

**Comment by thomsonimjd** [comment] 2018-01-11 05:50
I just referred the #557 which is to send the ether not for the token transfer. I would like to know if there is any contract in open zeppelin to tranfer tokens as a profit sharing for holding tokens.
