### ISSUE TITLE
Error: Definition of base has to precede definition of derived contract contract MintableToken is StandardToken, Ownable

### ISSUE THREAD

**Issue by parsparab** [OpenZeppelin/zeppelin-solidity#421] opened 2017-09-02 16:47 UTC
Error: Definition of base has to precede definition of derived contract
contract MintableToken is StandardToken, Ownable

**Comment by frangio** [comment] 2017-09-02 20:42
Hi @parsparab, thanks for reporting! What version of Solidity are you using?

**Comment by parsparab** [comment] 2017-09-03 14:00
Hi @frangio , I'm using pragma solidity ^0.4.11; version, I guess which is compatible with all latest files.

**Comment by frangio** [comment] 2017-09-04 03:27
But can you tell us what specific compiler version produced this error? You can find out by doing `truffle version` or `solc --version` perhaps.

**Comment by parsparab** [comment] 2017-09-04 03:37
I'm using solidity remix compiler.

**Comment by frangio** [comment] 2017-09-18 18:08
Closing because I haven't been able to reproduce the issue. I suspect @parsparab inlined their contracts in the wrong order.

**Closed by frangio** 2017-09-18 18:08 UTC
