### ISSUE TITLE
Can't install OpenZeppelin

### ISSUE THREAD

**Issue by eduinvestor** [OpenZeppelin/zeppelin-solidity#532] opened 2017-11-04 16:28 UTC
I have installed Truffle, but I cannot install the OpenZeppelin library.
I run "npm install zeppelin-solidity" in the console but I get this: 
![captura46](https://user-images.githubusercontent.com/30580652/32407183-7456f9ce-c185-11e7-9c7f-96250a9e09bb.PNG)

After that I created the folder C:Users/Pablo/package.json but now I get this 
![captura45](https://user-images.githubusercontent.com/30580652/32407192-97a23290-c185-11e7-823c-a43e00023660.PNG)

What can I do?

**Comment by GULSHAN-VASNANI** [comment] 2017-11-04 20:13
Hi,
Replace the contents of package.json file with the following :- 

{
  "name": "zeppelin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "zeppelin-solidity": "^1.3.0"
  }
}

After replacing,run :-  npm install zeppelin-solidity

**Comment by prahaladbelavadi** [comment] 2017-11-04 20:25
Hey @eduinvestor 
I'd suggest trying the following steps one more time:
- Change Working directory
```bash
cd ~/Desktop
mkdir openZeppelinSetup && cd openZeppelinSetup
```
- Initialize npm
```bash
npm init 
```
- Install both truffle and openzeppelin solidity
```bash
npm install --save zeppelin-solidity truffle
```
> Here's some [material](https://media.readthedocs.org/pdf/zeppelin-solidity/latest/zeppelin-solidity.pdf) to follow up post installation.

Cheers!

**Comment by KenoLeon** [comment] 2017-11-05 02:55
Still no luck with both suggestion, could it be related with Truffles new version, I am on:

Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)


And my errors:

npm WARN kenoleon@1.0.0 No description
npm WARN kenoleon@1.0.0 No repository field.

Do I need to init Nom if so what are the correct fields ? Thanks

**Comment by KenoLeon** [comment] 2017-11-05 05:14
So after playing around I found the package in my local node_modules which I think is the expected behavior,( still have to include them in a test) although the docs state "After that, you’ll get all the library’s contracts in the contracts/zeppelin folder" which I think is a bit misleading since it could refer to the initialized truffle dir.

**Comment by KenoLeon** [comment] 2017-11-05 18:08
New errors not finding contracts now... about to chew my arm in desperation !

 Just kidding, in the end this is what worked, still not sure this is the intended behavior, and the docs seems to need a bit of updating or maybe even rewriting cause they were not very clear (to me at least) , anyways:

Following this issue worked or me: https://github.com/OpenZeppelin/zeppelin-solidity/issues/409

So to install:

```
mkdir poneteLasPilasProject  && cd poneteLasPilasProject
npm init
truffle init
npm install zeppelin-solidity
truffle compile
```
This creates a node_modules inside poneteLasPilasProject with contracts, to access them within Truffle, ( the path in the docs is I believe incorrect):

```
pragma solidity ^0.4.0;

import "../node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol";

contract masPila {

}
```  

Cheers.

**Comment by Shrugs** [comment] 2017-11-06 16:13
@KenoLeon you can access them with just `import 'zeppelin-solidity/contracts/.....sol'`.

In general, it sounds like your node environment is a little wonky. It might be worth looking into nvm or some other node environment manager to isolate project environments (and you generally want to avoid `-g` unless it's a globally-useful tool like `yarn` or similar.

The warnings about "no repository field" and "no description" aren't important; those are commenting on the fact that your `package.json` doesn't specify that information. It's not truffle or open zeppelin related.

---

@eduinvestor did the following comments solve your issue?

**Comment by maraoz** [comment] 2017-11-11 00:33
> poneteLasPilasProject
:heart: 

Closing as this seems to be solved.
@eduinvestor if you think the docs are outdated please send a PR to improve them!

**Closed by maraoz** 2017-11-11 00:33 UTC
