### ISSUE TITLE
Anyone can call refund function in RefundVault.sol with anyone's address

### ISSUE THREAD

**Issue by nedodn** [OpenZeppelin/zeppelin-solidity#530] opened 2017-10-31 23:07 UTC
In RefundVault.sol the refund function is public without any other modifiers on it allowing anyone to call refund() with any address. Deposited funds would be returned to the investor but this would still be considered malicious I think. Please correct if I am wrong.

**Comment by frangio** [comment] 2017-11-02 02:41
Hi @nedodn! Thanks for reaching out.

This is actually by design. Can you explain why you would consider it malicious?

**Comment by nedodn** [comment] 2017-11-02 03:08
I guess mainly I was thinking that if an investor did not want to pull out of the crowdsale, they could be forced out by someone else, which might be more mischievous than malicious. But if you're assuming that since the crowdsale failed or didn't reach its goal that everyone wants out then it probably wouldn't be a big deal.

**Comment by frangio** [comment] 2017-11-02 03:17
Yes we're actually not only _assuming_ it, we're enforcing it!

Closing this issue then!

**Closed by frangio** 2017-11-02 03:17 UTC
