### ISSUE TITLE
Network state unknown  out of gas

### ISSUE THREAD

**Issue by thomsonimjd** [OpenZeppelin/zeppelin-solidity#621] opened 2017-12-21 10:08 UTC
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: out of gas
 at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
 at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:331156:36
 at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:175492:11
 at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:314196:9
 at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
 at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
 at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
 at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
 at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
 at emitNone (events.js:111:20)

**Comment by Shrugs** [comment] 2017-12-24 15:44
1. This isn't enough information for anyone to be able to help you.
2. Github issues are not the correct forum for this. Please reach out in one of the many gitter channels or in the OpenZeppelin #beginners channel for help.

Closing.

**Closed by Shrugs** 2017-12-24 15:44 UTC

**Comment by leochan007** [comment] 2017-12-27 05:31
i got this: The contract code couldn't be stored, please check your gas amount

**Comment by Shrugs** [comment] 2017-12-27 14:35
This error can be caused by many different things. In your case, @leochan007 it seems like the contract you're deploying requires enough gas that either 

1. your transaction to deploy it isn't providing enough gas
2. your testnet doesn't have a high enough gas limit.

The first thing I would do here is update truffle's gas limit to mainnets (currently about 8 million).

in `truffle.js`, add the `gas: 8000000` parameter to your network configuration

**Comment by leochan007** [comment] 2017-12-27 17:22
@Shrugs the contract is quite simple.
-----------------------------------------------------
pragma solidity ^0.4.18;

import 'zeppelin-solidity/contracts/token/CappedToken.sol';

contract LCToken is CappedToken {
}
-------------------------------------------------------
var LCToken = artifacts.require("./LCToken.sol");

module.exports = function(deployer) {

  deployer.deploy(LCToken);
};
---------------------------------------------------------
truffle.js
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 7545,
      gas: 8000000,
      network_id: "*",
    }
  }
};
------------------------------------------
using ganache ..gas limit 1000000000.......0...


tip:
as u know that, CappedToken has import many other contracts.
do i need to deploy all other contracts then link them together?

just like the example:

  deployer.deploy(ConvertLib);
  deployer.link(ConvertLib, MetaCoin);
  deployer.deploy(MetaCoin);

**Comment by Shrugs** [comment] 2017-12-28 17:23
The linking is only required in the case of a [solidity library](http://solidity.readthedocs.io/en/develop/contracts.html#libraries), so that won't be the case. When compiling a contract, the resulting bytecode includes all of the logic of the contracts that it inherited from, so no problems there.

@leochan007 which command are you running, specifically? Can you try `truffle migrate --network development`?

But everything looks pretty fine to me. Can you try using [ganache](https://github.com/trufflesuite/ganache) as your local testnet and confirm that it's using a gas limit (changed in the settings tab) of 8 million? (note that ganache runs on a separate port than testrpc, so you'll have to update that in your config file.

**Comment by leochan007** [comment] 2017-12-29 03:03
thx for your help about library linking.

btw,  "--network development" is the default option cause there is only one network. ganache works well on port 7545 which i config in truffle.js.  I saw the Migration deployed.  but it failed to deploy LcToken. :(
@Shrugs

**Comment by Shrugs** [comment] 2017-12-31 14:15
@leochan007 Figured it out here! https://github.com/OpenZeppelin/zeppelin-solidity/issues/629#issuecomment-354606049
