### ISSUE TITLE
truffle compile error: could not find zeppelin-solidity/contracts/...

### ISSUE THREAD

**Issue by roynalnaruto** [OpenZeppelin/zeppelin-solidity#409] opened 2017-08-27 05:31 UTC
I can see `zeppelin-solidity` in the /usr/local/lib/node_modules on my mac.
I created project with `truffle init`, but in one of my contracts, I cannot import the zeppelin contracts successfully.

```
pragma solidity 0.4.15;
import "zeppelin-solidity/contracts/token/MintableToken.sol";
contract SampleToken is MintableToken {
  string public name = "SampleToken";
  string public symbol = "SMT";
  uint256 public decimals = 1;
}
```

on `truffle compile` I get the following output:
```
Error: Could not find zeppelin-solidity/contracts/token/MintableToken.sol from any sources; imported from /Users/username/Develop/project/project-core/contracts/Tokens/SampleToken.sol
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:49111:23
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:60660:16
    at next (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:69109:18)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:49099:7
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:96498:5
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:69014:16
    at replenish (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60630:25)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60620:17)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:60660:16
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:96494:14)
```

the versions are:
Truffle v3.4.9
npm 3.10.10
solcjs 0.4.15+commit.bbb8e64f.Emscripten.clang

**Comment by frangio** [comment] 2017-08-28 17:32
Can you try installing OpenZeppelin locally (instead of globally)? I agree that this should work but it seems to be a problem with Truffle not considering global node modules. We should report this to the Truffle project if it hasn't already been reported.

**Comment by ravikiransharvirala** [comment] 2017-08-29 07:41
Same issue for me too(Error: Could not find zeppelin-solidity/contracts/token/MintableToken.sol). I installed OpenZeppelin locally

**Comment by sh4ka** [comment] 2017-09-01 14:55
@roynalnaruto Can you try with single quotes instead?

**Comment by param087** [comment] 2017-09-11 01:46
same issue for me too if any one find answer please let us know

**Comment by roynalnaruto** [comment] 2017-09-11 04:05
@sh4ka no, I tried that too. Did not work.

**Comment by gvoicu** [comment] 2017-09-11 21:38
@roynalnaruto @param087: One solution that works for me until this will be fixed is to add also the `node_modules` folder to the relative path.

For example, instead of `import 'zeppelin-solidity/contracts/token/MintableToken.sol'`
I did: `import '../../node_modules/zeppelin-solidity/contracts/token/MintableToken.sol'`

**Comment by frangio** [comment] 2017-09-18 18:20
Can anyone having this issue please share an example repo where I can reproduce the problem? I suspect this was caused by doing a global install (`npm install -g zeppelin-solidity`) which Truffle doesn't support.

I've opened an issue for it trufflesuite/truffle-resolver#4.

**Closed by frangio** 2017-09-18 18:20 UTC

**Comment by AlekseiStalker** [comment] 2017-10-11 14:56
I have the same problem. 

 "->'  
and 
 import '../../node_modules/zeppelin-solidity/contracts/token/MintableToken.sol'

did not help

**Comment by abramjs** [comment] 2017-10-26 00:44
I resolved the same problem with: _npm init_
so now the sequence is:

_npm init
truffle init
npm install zeppelin-solidity
truffle compile_

hope it would helps

**Comment by hahaelx** [comment] 2018-01-30 04:31
zeppelin-solidity changed directory structure in new version,
it should be:
```
import 'zeppelin-solidity/contracts/token/ERC20/MintableToken.sol';
```

**Comment by epinal** [comment] 2018-02-06 16:15
Truffle doesn't find the global module. I fixed this way:

In the project folder:
_npm init_

// Install the zeppelin-solidity module locally 
_npm install zeppelin-solidity_

// Then compile
_truffle compile_

**Comment by chenyulzhh** [comment] 2018-03-16 02:49
想知道有多少人碰到这个问题是因为从网上抄过时的代码导致的，正如@hahaelx 所说的那样新版本zeppelin-solidity里 token目录下面新增了一层目录 ERC20

Sorry for my poor english，translated with Baidu:

I want to know how many people encounter this problem because of the outdated code from the Internet. As @hahaelx said, as a result of the new version of zeppelin-solidity, there is a new directory ERC20 under the token directory.

**Comment by hiyouke** [comment] 2018-03-17 07:47
@chenyulzhh 你是个天才！这个totalSupply_后面加个下划线，目的是？

**Comment by chenyulzhh** [comment] 2018-03-26 09:14
@hiyouke 因为BasicToken类里面，定义的是 totalSupply_ ，估计是为了和 totalSupply() 这个public的方法区分开吧。。

**Comment by smakintel** [comment] 2018-06-24 13:57
remove openzeppelin to zepplin that worked for me

**Comment by iamhimmat89** [comment] 2020-06-30 13:06
Please check zeppeline / openzeppelin version and then check corresponding node_module folder whether mentioned module file is available or not else change your import path

**Comment by nisha0712** [comment] 2020-07-27 12:47
Could not find openzeppelin/contracts/ownership/Ownable.sol from any sources; 

can anyone resolve it?

**Comment by frangio** [comment] 2020-07-27 15:27
For anyone who is having this issue, we're happy to help, but there are many potential causes so we need to know more details about your environment, your dependencies, etc.

Please share all of this information in a new post at [forum.openzeppelin.com](https://forum.openzeppelin.com) and we'll help you figure it out.
